server:
  port: 9192

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/QuizzReact
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      format_sql: true
